cloudinary:
    api-key: 457794879566673
    api-secret: ${CLOUDINARY}
    cloud-name: b1gted0
logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
server:
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                servlet:
                    multipart:
                        enabled: true
                        max-file-size: 5MB
                        max-request-size: 5MB
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        jpa:
            hibernate:
                ddl-auto: update
            open-in-view: false
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL8Dialect
                    format_sql: true
                    servlet:
                        multipart:
                            enabled: true
                            max-file-size: 10MB
                            max-request-size: 10MB
        password: gotin2002
        url: jdbc:mysql://localhost:3306/baseball_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
